Fix EqualsAndHashCode Annotation Warning Messages
Bit-Quill/opensearch-project-sql pull request #120
Opened 2022-09-19 18:24 UTC by GabeFernandez310

Signed-off-by: Gabriel Fernandez <gabrielf@Unused19-MacBook.local>

### Description
Fix warning messages in GitHub actions associated with EqualsAndHashCode annotations.

 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass, including unit test, integration test and doctest
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
  - [ ] New functionality has user manual doc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-09-19 20:00 UTC, MitchellGale-BitQuill approved these changes
Looks good to me!

2022-09-19 20:03 UTC, forestmvey approved these changes

2022-09-19 20:32 UTC, MaxKsyunz requested changes
@GabeFernandez310 could you setup your `git.username` and `git.email` as well as GitHub profile to a globally addressable email address instead of `*.local`?

[Here's](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/setting-your-commit-email-address) GitHub help on the matter.

If you'd like to use a private email, GitHub generates one for you as well.

2022-09-19 22:47 UTC, MaxKsyunz approved these changes

2022-09-19 22:50 UTC, merged

2022-09-28 16:42 UTC, MitchellGale-BitQuill commented
Hey @GabeFernandez310,
`core/src/main/java/org/opensearch/sql/ast/tree/Limit.java:20: warning: Generating equals/hashCode implementation but without a call to superclass, even though this class does not extend java.lang.Object. If this is intentional, add '@EqualsAndHashCode(callSuper=false)' to your type.
@EqualsAndHashCode`

`/core/src/main/java/org/opensearch/sql/expression/ParseExpression.java:25: warning: Generating equals/hashCode implementation but without a call to superclass, even though this class does not extend java.lang.Object. If this is intentional, add '@EqualsAndHashCode(callSuper=false)' to your type.
@EqualsAndHashCode`

Looks like there are two more calls to `EqualsAndHashCode` that didn't get updated. Could you please see about updating them.