[WIP:] Add CBRT to the V2 engine
Bit-Quill/opensearch-project-sql pull request #166
Opened 2022-11-15 00:15 UTC by margarit-h

Signed-off-by: Margarit Hakobyan <margarith@bitquilltech.com>

### Description
Adds CBRT() math function to the V2 engine.

Usage: CBRT(number) calculates the cube root of a non-negative number
Argument type: INTEGER/LONG/FLOAT/DOUBLE
Return type: DOUBLE

(Non-negative) INTEGER/LONG/FLOAT/DOUBLE -> DOUBLE
(Negative) INTEGER/LONG/FLOAT/DOUBLE -> NULL

Example::

    opensearchsql> SELECT CBRT(8), CBRT(9.261);
    fetched rows / total rows = 1/1
    +-----------+---------------+
      | CBRT(8)   |   CBRT(9.261)  |
      |-----------+---------------|
      | 2.0             |          2.1           |
    +-----------+---------------+
 
### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [x] New functionality includes testing.
  - [ ] All tests pass, including unit test, integration test and doctest
- [x] New functionality has been documented.
  - [ ] New functionality has javadoc added
  - [ ] New functionality has user manual doc added
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-11-15 01:59 UTC, Yury-Fridlyand requested changes

2022-11-15 01:59 UTC, Yury-Fridlyand commented on core/src/main/java/org/opensearch/sql/expression/operator/arthmetic/MathematicalFunction.java
> +                v -> v.doubleValue() < 0 ? ExprNullValue.of() :
Function should accept negative numbers too:
```math
\sqrt[3]{-8}=-2
```

2022-11-15 01:59 UTC, Yury-Fridlyand commented on core/src/main/java/org/opensearch/sql/expression/operator/arthmetic/MathematicalFunction.java
> +                v -> v.doubleValue() < 0 ? ExprNullValue.of() :
```math
\sqrt[3]{-8}=-2
```

2022-11-15 19:27 UTC, acarbonetto commented on core/src/test/java/org/opensearch/sql/expression/operator/arthmetic/MathematicalFunctionTest.java
> +  @ValueSource(longs = {1L, 2L})
we could also test negative longs, and larger-than-2 longs

2022-11-15 19:27 UTC, acarbonetto commented on core/src/test/java/org/opensearch/sql/expression/operator/arthmetic/MathematicalFunctionTest.java
> +  @ValueSource(ints = {1, 2})
negative integers?

2022-11-15 19:27 UTC, acarbonetto commented on core/src/test/java/org/opensearch/sql/expression/operator/arthmetic/MathematicalFunctionTest.java
> +  @ValueSource(floats = {1F, 2F})
negative floats, or floats with more precision?

2022-11-15 19:27 UTC, acarbonetto commented on core/src/test/java/org/opensearch/sql/expression/operator/arthmetic/MathematicalFunctionTest.java
> +  @ValueSource(doubles = {1D, 2D})
larger doubles, doubles with values below the decimal?

2022-11-15 21:37 UTC, MaxKsyunz approved these changes

2022-11-16 18:45 UTC, GumpacG approved these changes

2022-11-16 22:14 UTC, forestmvey approved these changes

2022-11-16 23:06 UTC, acarbonetto approved these changes

2022-11-16 23:27 UTC, merged