Add reverse() string function to V2
Bit-Quill/opensearch-project-sql pull request #183
Opened 2022-12-06 19:34 UTC by margarit-h

Signed-off-by: Margarit Hakobyan <margarith@bitquilltech.com>

### Description
Usage: REVERSE(str) returns reversed string of the string supplied as an argument. Returns NULL if the argument is NULL.

Argument type: STRING

Return type: STRING

Example::

    os> SELECT REVERSE('abcde')
    fetched rows / total rows = 1/1
    +--------------------+
    | REVERSE('abcde')   |
    |--------------------|
    | edcba              |
    +--------------------+

Example::

    os> source=people | eval `REVERSE('abcde')` = REVERSE('abcde') | fields `REVERSE('abcde')`
    fetched rows / total rows = 1/1
    +--------------------+
    | REVERSE('abcde')   |
    |--------------------|
    | edcba              |
    +--------------------+
 
### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [x] New functionality includes testing.
  - [x] All tests pass, including unit test, integration test and doctest
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
  - [x] New functionality has user manual doc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-12-06 21:13 UTC, acarbonetto requested changes

2022-12-06 21:13 UTC, acarbonetto commented on core/src/main/java/org/opensearch/sql/expression/function/BuiltinFunctionName.java
> +  REVERSE(FunctionName.of("reverse")),
Please move up to be after REPLACE

2022-12-06 21:13 UTC, acarbonetto commented on docs/user/dql/functions.rst
> +Usage: REVERSE(str) returns reversed string of the string supplied as an argument. Returns NULL if the argument is NULL.
Since we're mentioning it here, we should add the NULL case to the test below

2022-12-06 21:13 UTC, acarbonetto commented on docs/user/ppl/functions/string.rst
> +Usage: REVERSE(str) returns reversed string of the string supplied as an argument. Returns NULL if the argument is NULL.
Since we're mentioning it here, we should add the NULL case to the test below

2022-12-06 21:13 UTC, acarbonetto commented on integ-test/src/test/java/org/opensearch/sql/sql/TextFunctionIT.java
> +    verifyQuery("reverse('')", "keyword", "");
null case?

2022-12-07 21:24 UTC, Yury-Fridlyand approved these changes

2022-12-07 22:13 UTC, acarbonetto approved these changes

2022-12-08 03:12 UTC, GumpacG approved these changes

2022-12-08 21:31 UTC, MitchellGale-BitQuill approved these changes

2022-12-09 15:56 UTC, GabeFernandez310 approved these changes

2022-12-09 17:30 UTC, merged