Update BI connectors and drivers readme files
Bit-Quill/opensearch-project-sql pull request #80
Opened 2022-06-24 00:26 UTC by Yury-Fridlyand

Signed-off-by: Yury Fridlyand <yuryf@bitquilltech.com>

* Update `readme`s
* Add connectors' binaries
* Add connectors' download links
* Add drivers' download links
* Reorganize connectors' file tree
* Update GHA workflow

2022-06-27 12:24 UTC, acarbonetto requested changes

2022-06-27 12:24 UTC, acarbonetto commented on bi-connectors/PowerBIConnector/README.md
> +The most recent build could be donwloaded from an automated CI workflow: [link](https://github.com/opensearch-project/sql/actions/workflows/bi-connectors.yml).
`The most recent build could be donwloaded from an automated CI workflow`
to:
`The Power BI connector is available to be downloaded from the automated CI workflow`

2022-06-27 12:24 UTC, acarbonetto commented on bi-connectors/TableauConnector/README.md
> +The most recent build could be donwloaded from an automated CI workflow: [link](https://github.com/opensearch-project/sql/actions/workflows/bi-connectors.yml).
Recommend changing from: 
`The most recent build could be donwloaded from an automated CI workflow`
to:
`The Tableau connector is available to be downloaded from the automated CI workflow`

2022-06-27 12:24 UTC, acarbonetto commented on sql-jdbc/README.md
> +The driver is available for download from an [automated CI workflow](https://github.com/opensearch-project/sql/actions/workflows/sql-jdbc-test-and-build-workflow.yml) and from [Artifacts page](https:
Can you swap the ordering?  We should recommend that the JDBC driver be downloaded from the artifacts directory first.

2022-06-27 12:24 UTC, acarbonetto commented on sql-jdbc/README.md
> +The driver is available for download from an [automated CI workflow](https://github.com/opensearch-project/sql/actions/workflows/sql-jdbc-test-and-build-workflow.yml) and from [Artifacts page](https:
Also, please remove 'an' from: `The driver is available for download from an`

2022-06-27 12:24 UTC, acarbonetto commented on sql-odbc/README.md
> +They are available for download from an [automated CI workflow](https://github.com/opensearch-project/sql/actions/workflows/sql-odbc-main.yml) and from [Artifacts page](https://opensearch.org/artifac
Same. 
Please swap the order. 
Remove 'an' from `They are available for download from an`.

2022-06-28 19:17 UTC, acarbonetto approved these changes

2022-06-28 19:19 UTC, acarbonetto commented on sql-jdbc/README.md
> +The driver is available for download from [Artifacts page](https://opensearch.org/artifacts) on OpenSearch.org at the very bottom from and [automated CI workflow](https://github.com/opensearch-projec
switch `from and` to `and from` at the end of the line

2022-06-28 19:19 UTC, MaxKsyunz approved these changes

2022-06-28 19:20 UTC, acarbonetto commented on sql-odbc/README.md
> +They are available for download from [Artifacts page](https://opensearch.org/artifacts) on OpenSearch.org at the very bottom from and [automated CI workflow](https://github.com/opensearch-project/sql
at the end of the line: switch `from and` to `and from`

2022-06-28 20:36 UTC, forestmvey approved these changes

2022-06-28 21:05 UTC, merged